/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentId } from './assignment-id'
import type { CourseId } from './course-id'
import type { ProgramId } from './program-id'
import type { SemesterId } from './semester-id'
import type { StaffId } from './staff-id'
import type { TeachingLoad } from './teaching-load'

export interface ApprovedAssignment {
  id?: AssignmentId
  courseId?: CourseId
  courseName?: string
  programId?: ProgramId
  programName?: string
  semesterId?: SemesterId
  primaryLecturerId?: StaffId
  primaryLecturerName?: string
  tutorId?: StaffId
  tutorName?: string
  teachingLoad?: TeachingLoad
  expectedStudentCount?: number
  year?: number
  session?: number
  groupName?: string
}
