/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { RoomEntry } from './room-entry'

export interface BlockEntry {
  blockId?: number
  blockName?: string
  blockInitial?: string
  rooms?: RoomEntry[]
}
