/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CohortView {
  id?: string
  label?: string
  programId?: string
  programName?: string
  year?: number
  session?: number
}
