/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ConflictSummaryView {
  conflictId?: string
  conflictType?: string
  conflictingEntryId?: string
  incumbentEntryId?: string
  conflictingCourseName?: string
  incumbentCourseName?: string
  resolved?: boolean
  resolvedAt?: string
}
