/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface CreateTimetableRequest {
  cohortId?: string
  /** @minLength 1 */
  programId: string
  /** @minLength 1 */
  programName: string
  /** @minLength 1 */
  semesterId: string
  /** @minLength 1 */
  semesterName: string
  /** @minimum 1 */
  year?: number
  /** @minimum 1 */
  session?: number
}
