/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface EntryView {
  entryId?: string
  assignmentId?: string
  courseName?: string
  courseCode?: string
  primaryLecturerName?: string
  tutorName?: string
  roomName?: string
  deliveryMode?: string
  category?: string
  practical?: boolean
  hasConflict?: boolean
  conflictIds?: string[]
}
