/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export * from './approved-assignment'
export * from './assignment-id'
export * from './block-entry'
export * from './conflict-summary-view'
export * from './course-id'
export * from './create-timetable-request'
export * from './department-entry'
export * from './entry-view'
export * from './faculty-group'
export * from './faculty-group-faculty-type'
export * from './get-all-asignments-params'
export * from './legacy-campus-room-group'
export * from './legacy-department-response'
export * from './legacy-lesson-slot-group'
export * from './list-timetables-params'
export * from './move-entry-request'
export * from './place-entry-request'
export * from './program-id'
export * from './publish-request'
export * from './resolve-conflict-request'
export * from './room-entry'
export * from './semester-id'
export * from './slot-day-entry'
export * from './slot-view'
export * from './staff-id'
export * from './teaching-load'
export * from './timetable-grid-view'
export * from './timetable-list-item-view'
