/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FacultyGroup } from './faculty-group'

export interface LegacyDepartmentResponse {
  campusName?: string
  faculties?: FacultyGroup[]
}
