/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BlockEntry } from './block-entry'

export interface LegacyCampusRoomGroup {
  campusId?: number
  campusName?: string
  campusCode?: string
  blocks?: BlockEntry[]
}
