/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SlotDayEntry } from './slot-day-entry'

export interface LegacyLessonSlotGroup {
  lessonId?: number
  lessonName?: string
  startTime?: string
  endTime?: string
  studyType?: string
  slots?: SlotDayEntry[]
}
