/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface LegacyCohortResponse {
  programId?: number
  programName?: string
  abbreviation?: string
  departmentId?: number
  facultyId?: number
  campusId?: number
  year?: number
  session?: number
  label?: string
  studyType?: string
  assignmentCount?: number
}
