/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MoveEntryRequestNewDay } from './move-entry-request-new-day'
import type { MoveEntryRequestNewDeliveryMode } from './move-entry-request-new-delivery-mode'

export interface MoveEntryRequest {
  newDay: MoveEntryRequestNewDay
  newStartTime: string
  newEndTime: string
  newDeliveryMode: MoveEntryRequestNewDeliveryMode
  newRoomId?: string
}
