/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PlaceEntryRequestDay } from './place-entry-request-day'
import type { PlaceEntryRequestDeliveryMode } from './place-entry-request-delivery-mode'

export interface PlaceEntryRequest {
  /** @minLength 1 */
  assignmentId: string
  day: PlaceEntryRequestDay
  startTime: string
  endTime: string
  deliveryMode: PlaceEntryRequestDeliveryMode
  roomId?: string
  /** @minLength 1 */
  primaryLecturerId: string
  tutorId?: string
  /** @minLength 1 */
  placedByStaffId: string
}
