/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PlaceEntryRequest {
  /** @minLength 1 */
  assignmentId: string
  /** @minLength 1 */
  timeSlotId: string
  roomId?: string
  /** @minLength 1 */
  primaryLecturerId: string
  tutorId?: string
  /** @minLength 1 */
  placedByStaffId: string
}
