/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntryView } from './entry-view'

export interface SlotView {
  timeSlotId?: string
  day?: string
  periodLabel?: string
  startTime?: string
  endTime?: string
  blocked?: boolean
  entry?: EntryView
}
