/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BlockedWindowView } from './blocked-window-view'
import type { SlotView } from './slot-view'

export interface TimetableGridView {
  timetableId?: string
  programName?: string
  semesterName?: string
  year?: number
  session?: number
  status?: string
  unresolvedConflictCount?: number
  viewportStart?: string
  viewportEnd?: string
  blockedWindows?: BlockedWindowView[]
  slots?: SlotView[]
}
