/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TimetableListItemView {
  id?: string
  programId?: string
  programName?: string
  semesterId?: string
  semesterName?: string
  year?: number
  session?: number
  status?: string
  entryCount?: number
  unresolvedConflictCount?: number
}
