import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse,
} from 'axios'

import type {
  ApprovedAssignment,
  ConflictSummaryView,
  CreateTimetableRequest,
  GetAllAsignmentsParams,
  LegacyCampusRoomGroup,
  LegacyDepartmentResponse,
  LegacyLessonSlotGroup,
  ListTimetablesParams,
  MoveEntryRequest,
  PlaceEntryRequest,
  PublishRequest,
  ResolveConflictRequest,
  SlotView,
  TimetableGridView,
  TimetableListItemView,
} from './models'
/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery,
} from '@tanstack/react-query'

import * as axios from 'axios'

export function listTimetables(params?: ListTimetablesParams, options?: AxiosRequestConfig): Promise<AxiosResponse<TimetableListItemView[]>> {
  return axios.default.get(
    `http://localhost:8080/api/timetables`,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  )
}

export function getListTimetablesQueryKey(params?: ListTimetablesParams) {
  return [
    `http://localhost:8080/api/timetables`,
    ...(params ? [params] : []),
  ] as const
}

export function getListTimetablesQueryOptions<TData = Awaited<ReturnType<typeof listTimetables>>, TError = AxiosError<unknown>>(params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListTimetablesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTimetables>>> = ({ signal }) => listTimetables(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTimetablesQueryResult = NonNullable<Awaited<ReturnType<typeof listTimetables>>>
export type ListTimetablesQueryError = AxiosError<unknown>

export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = AxiosError<unknown>>(
  params: undefined | ListTimetablesParams, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof listTimetables>>,
      TError,
      Awaited<ReturnType<typeof listTimetables>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = AxiosError<unknown>>(
  params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof listTimetables>>,
      TError,
      Awaited<ReturnType<typeof listTimetables>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = AxiosError<unknown>>(
  params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = AxiosError<unknown>>(
  params?: ListTimetablesParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTimetablesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function createTimetable(createTimetableRequest: CreateTimetableRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables`,
    createTimetableRequest,
    {
      ...options,
    },
  )
}

export function getCreateTimetableMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext> {
  const mutationKey = ['createTimetable']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTimetable>>, { data: CreateTimetableRequest }> = (props) => {
    const { data } = props ?? {}

    return createTimetable(data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateTimetableMutationResult = NonNullable<Awaited<ReturnType<typeof createTimetable>>>
export type CreateTimetableMutationBody = CreateTimetableRequest
export type CreateTimetableMutationError = AxiosError<unknown>

export function useCreateTimetable<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createTimetable>>,
  TError,
  { data: CreateTimetableRequest },
  TContext
> {
  return useMutation(getCreateTimetableMutationOptions(options), queryClient)
}

export function unpublish(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/unpublish`,
    undefined,
    options,
  )
}

export function getUnpublishMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['unpublish']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof unpublish>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return unpublish(timetableId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UnpublishMutationResult = NonNullable<Awaited<ReturnType<typeof unpublish>>>

export type UnpublishMutationError = AxiosError<unknown>

export function useUnpublish<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof unpublish>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getUnpublishMutationOptions(options), queryClient)
}

export function returnToDraft(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/return-to-draft`,
    undefined,
    options,
  )
}

export function getReturnToDraftMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['returnToDraft']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof returnToDraft>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return returnToDraft(timetableId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReturnToDraftMutationResult = NonNullable<Awaited<ReturnType<typeof returnToDraft>>>

export type ReturnToDraftMutationError = AxiosError<unknown>

export function useReturnToDraft<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof returnToDraft>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getReturnToDraftMutationOptions(options), queryClient)
}

export function publish(timetableId: string, publishRequest: PublishRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/publish`,
    publishRequest,
    options,
  )
}

export function getPublishMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext> {
  const mutationKey = ['publish']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof publish>>, { timetableId: string, data: PublishRequest }> = (props) => {
    const { timetableId, data } = props ?? {}

    return publish(timetableId, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PublishMutationResult = NonNullable<Awaited<ReturnType<typeof publish>>>
export type PublishMutationBody = PublishRequest
export type PublishMutationError = AxiosError<unknown>

export function usePublish<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { timetableId: string, data: PublishRequest },
  TContext
> {
  return useMutation(getPublishMutationOptions(options), queryClient)
}

export function forward(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/forward`,
    undefined,
    options,
  )
}

export function getForwardMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['forward']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof forward>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return forward(timetableId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ForwardMutationResult = NonNullable<Awaited<ReturnType<typeof forward>>>

export type ForwardMutationError = AxiosError<unknown>

export function useForward<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof forward>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getForwardMutationOptions(options), queryClient)
}

export function placeEntry(timetableId: string, placeEntryRequest: PlaceEntryRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<string>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/entries`,
    placeEntryRequest,
    {
      ...options,
    },
  )
}

export function getPlaceEntryMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext> {
  const mutationKey = ['placeEntry']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeEntry>>, { timetableId: string, data: PlaceEntryRequest }> = (props) => {
    const { timetableId, data } = props ?? {}

    return placeEntry(timetableId, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PlaceEntryMutationResult = NonNullable<Awaited<ReturnType<typeof placeEntry>>>
export type PlaceEntryMutationBody = PlaceEntryRequest
export type PlaceEntryMutationError = AxiosError<unknown>

export function usePlaceEntry<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof placeEntry>>,
  TError,
  { timetableId: string, data: PlaceEntryRequest },
  TContext
> {
  return useMutation(getPlaceEntryMutationOptions(options), queryClient)
}

export function resolveConflict(timetableId: string, conflictId: string, resolveConflictRequest: ResolveConflictRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.post(
    `http://localhost:8080/api/timetables/${timetableId}/conflicts/${conflictId}/resolve`,
    resolveConflictRequest,
    options,
  )
}

export function getResolveConflictMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext> {
  const mutationKey = ['resolveConflict']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveConflict>>, { timetableId: string, conflictId: string, data: ResolveConflictRequest }> = (props) => {
    const { timetableId, conflictId, data } = props ?? {}

    return resolveConflict(timetableId, conflictId, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResolveConflictMutationResult = NonNullable<Awaited<ReturnType<typeof resolveConflict>>>
export type ResolveConflictMutationBody = ResolveConflictRequest
export type ResolveConflictMutationError = AxiosError<unknown>

export function useResolveConflict<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof resolveConflict>>,
  TError,
  { timetableId: string, conflictId: string, data: ResolveConflictRequest },
  TContext
> {
  return useMutation(getResolveConflictMutationOptions(options), queryClient)
}

export function moveEntry(timetableId: string, entryId: string, moveEntryRequest: MoveEntryRequest, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.patch(
    `http://localhost:8080/api/timetables/${timetableId}/entries/${entryId}/move`,
    moveEntryRequest,
    options,
  )
}

export function getMoveEntryMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext> {
  const mutationKey = ['moveEntry']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveEntry>>, { timetableId: string, entryId: string, data: MoveEntryRequest }> = (props) => {
    const { timetableId, entryId, data } = props ?? {}

    return moveEntry(timetableId, entryId, data, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoveEntryMutationResult = NonNullable<Awaited<ReturnType<typeof moveEntry>>>
export type MoveEntryMutationBody = MoveEntryRequest
export type MoveEntryMutationError = AxiosError<unknown>

export function useMoveEntry<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof moveEntry>>,
  TError,
  { timetableId: string, entryId: string, data: MoveEntryRequest },
  TContext
> {
  return useMutation(getMoveEntryMutationOptions(options), queryClient)
}

export function getTimetableGrid(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<TimetableGridView>> {
  return axios.default.get(
    `http://localhost:8080/api/timetables/${timetableId}`,
    options,
  )
}

export function getGetTimetableGridQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}`,
  ] as const
}

export function getGetTimetableGridQueryOptions<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = AxiosError<unknown>>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetTimetableGridQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimetableGrid>>> = ({ signal }) => getTimetableGrid(timetableId, { signal, ...axiosOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTimetableGridQueryResult = NonNullable<Awaited<ReturnType<typeof getTimetableGrid>>>
export type GetTimetableGridQueryError = AxiosError<unknown>

export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = AxiosError<unknown>>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getTimetableGrid>>,
      TError,
      Awaited<ReturnType<typeof getTimetableGrid>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getTimetableGrid>>,
      TError,
      Awaited<ReturnType<typeof getTimetableGrid>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = AxiosError<unknown>>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTimetableGridQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getConflicts(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<ConflictSummaryView[]>> {
  return axios.default.get(
    `http://localhost:8080/api/timetables/${timetableId}/conflicts`,
    options,
  )
}

export function getGetConflictsQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}/conflicts`,
  ] as const
}

export function getGetConflictsQueryOptions<TData = Awaited<ReturnType<typeof getConflicts>>, TError = AxiosError<unknown>>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetConflictsQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConflicts>>> = ({ signal }) => getConflicts(timetableId, { signal, ...axiosOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConflictsQueryResult = NonNullable<Awaited<ReturnType<typeof getConflicts>>>
export type GetConflictsQueryError = AxiosError<unknown>

export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = AxiosError<unknown>>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getConflicts>>,
      TError,
      Awaited<ReturnType<typeof getConflicts>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getConflicts>>,
      TError,
      Awaited<ReturnType<typeof getConflicts>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = AxiosError<unknown>>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConflictsQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getAvailableSlots(timetableId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<SlotView[]>> {
  return axios.default.get(
    `http://localhost:8080/api/timetables/${timetableId}/available-slots`,
    options,
  )
}

export function getGetAvailableSlotsQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}/available-slots`,
  ] as const
}

export function getGetAvailableSlotsQueryOptions<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = AxiosError<unknown>>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAvailableSlotsQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailableSlots>>> = ({ signal }) => getAvailableSlots(timetableId, { signal, ...axiosOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailableSlots>>>
export type GetAvailableSlotsQueryError = AxiosError<unknown>

export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = AxiosError<unknown>>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAvailableSlots>>,
      TError,
      Awaited<ReturnType<typeof getAvailableSlots>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAvailableSlots>>,
      TError,
      Awaited<ReturnType<typeof getAvailableSlots>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = AxiosError<unknown>>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = AxiosError<unknown>>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAvailableSlotsQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getSlots(options?: AxiosRequestConfig): Promise<AxiosResponse<LegacyLessonSlotGroup[]>> {
  return axios.default.get(
    `http://localhost:8080/api/acl/slots`,
    options,
  )
}

export function getGetSlotsQueryKey() {
  return [
    `http://localhost:8080/api/acl/slots`,
  ] as const
}

export function getGetSlotsQueryOptions<TData = Awaited<ReturnType<typeof getSlots>>, TError = AxiosError<unknown>>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSlotsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSlots>>> = ({ signal }) => getSlots({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getSlots>>>
export type GetSlotsQueryError = AxiosError<unknown>

export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = AxiosError<unknown>>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getSlots>>,
      TError,
      Awaited<ReturnType<typeof getSlots>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getSlots>>,
      TError,
      Awaited<ReturnType<typeof getSlots>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSlotsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getRooms(options?: AxiosRequestConfig): Promise<AxiosResponse<LegacyCampusRoomGroup[]>> {
  return axios.default.get(
    `http://localhost:8080/api/acl/rooms`,
    options,
  )
}

export function getGetRoomsQueryKey() {
  return [
    `http://localhost:8080/api/acl/rooms`,
  ] as const
}

export function getGetRoomsQueryOptions<TData = Awaited<ReturnType<typeof getRooms>>, TError = AxiosError<unknown>>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRoomsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRooms>>> = ({ signal }) => getRooms({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoomsQueryResult = NonNullable<Awaited<ReturnType<typeof getRooms>>>
export type GetRoomsQueryError = AxiosError<unknown>

export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = AxiosError<unknown>>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getRooms>>,
      TError,
      Awaited<ReturnType<typeof getRooms>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getRooms>>,
      TError,
      Awaited<ReturnType<typeof getRooms>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRoomsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getDepartments(options?: AxiosRequestConfig): Promise<AxiosResponse<LegacyDepartmentResponse[]>> {
  return axios.default.get(
    `http://localhost:8080/api/acl/departments`,
    options,
  )
}

export function getGetDepartmentsQueryKey() {
  return [
    `http://localhost:8080/api/acl/departments`,
  ] as const
}

export function getGetDepartmentsQueryOptions<TData = Awaited<ReturnType<typeof getDepartments>>, TError = AxiosError<unknown>>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDepartmentsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartments>>> = ({ signal }) => getDepartments({ signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getDepartments>>>
export type GetDepartmentsQueryError = AxiosError<unknown>

export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = AxiosError<unknown>>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getDepartments>>,
      TError,
      Awaited<ReturnType<typeof getDepartments>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getDepartments>>,
      TError,
      Awaited<ReturnType<typeof getDepartments>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = AxiosError<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDepartmentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function getAllAsignments(params: GetAllAsignmentsParams, options?: AxiosRequestConfig): Promise<AxiosResponse<ApprovedAssignment[]>> {
  return axios.default.get(
    `http://localhost:8080/api/acl/assignments`,
    {
      ...options,
      params: { ...params, ...options?.params },
    },
  )
}

export function getGetAllAsignmentsQueryKey(params?: GetAllAsignmentsParams) {
  return [
    `http://localhost:8080/api/acl/assignments`,
    ...(params ? [params] : []),
  ] as const
}

export function getGetAllAsignmentsQueryOptions<TData = Awaited<ReturnType<typeof getAllAsignments>>, TError = AxiosError<unknown>>(params: GetAllAsignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData>>, axios?: AxiosRequestConfig }) {
  const { query: queryOptions, axios: axiosOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllAsignmentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllAsignments>>> = ({ signal }) => getAllAsignments(params, { signal, ...axiosOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllAsignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllAsignments>>>
export type GetAllAsignmentsQueryError = AxiosError<unknown>

export function useGetAllAsignments<TData = Awaited<ReturnType<typeof getAllAsignments>>, TError = AxiosError<unknown>>(
  params: GetAllAsignmentsParams, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAllAsignments>>,
      TError,
      Awaited<ReturnType<typeof getAllAsignments>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAsignments<TData = Awaited<ReturnType<typeof getAllAsignments>>, TError = AxiosError<unknown>>(
  params: GetAllAsignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAllAsignments>>,
      TError,
      Awaited<ReturnType<typeof getAllAsignments>>
    >,
    'initialData'
  >, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAsignments<TData = Awaited<ReturnType<typeof getAllAsignments>>, TError = AxiosError<unknown>>(
  params: GetAllAsignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllAsignments<TData = Awaited<ReturnType<typeof getAllAsignments>>, TError = AxiosError<unknown>>(
  params: GetAllAsignmentsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAsignments>>, TError, TData>>, axios?: AxiosRequestConfig },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllAsignmentsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export function removeEntry(timetableId: string, entryId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
  return axios.default.delete(
    `http://localhost:8080/api/timetables/${timetableId}/entries/${entryId}`,
    options,
  )
}

export function getRemoveEntryMutationOptions<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext>, axios?: AxiosRequestConfig }): UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext> {
  const mutationKey = ['removeEntry']
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeEntry>>, { timetableId: string, entryId: string }> = (props) => {
    const { timetableId, entryId } = props ?? {}

    return removeEntry(timetableId, entryId, axiosOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveEntryMutationResult = NonNullable<Awaited<ReturnType<typeof removeEntry>>>

export type RemoveEntryMutationError = AxiosError<unknown>

export function useRemoveEntry<TError = AxiosError<unknown>, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext>, axios?: AxiosRequestConfig }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof removeEntry>>,
  TError,
  { timetableId: string, entryId: string },
  TContext
> {
  return useMutation(getRemoveEntryMutationOptions(options), queryClient)
}
