import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  ApprovedAssignment,
  ConflictSummaryView,
  CreateTimetableRequest,
  GetAllAssignmentsParams,
  GetCohortsParams,
  LegacyCampusRoomGroup,
  LegacyCohortResponse,
  LegacyDepartmentResponse,
  LegacyLessonSlotGroup,
  ListTimetablesParams,
  MoveEntryRequest,
  PlaceEntryRequest,
  PublishRequest,
  ResolveConflictRequest,
  SlotView,
  TimetableGridView,
  TimetableListItemView,
} from './models'

/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  useMutation,
  useQuery,
} from '@tanstack/react-query'

export interface listTimetablesResponse200 {
  data: TimetableListItemView[]
  status: 200
}

export type listTimetablesResponseSuccess = (listTimetablesResponse200) & {
  headers: Headers
}

export type listTimetablesResponse = (listTimetablesResponseSuccess)

export function getListTimetablesUrl(params?: ListTimetablesParams) {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/timetables?${stringifiedParams}` : `http://localhost:8080/api/timetables`
}

export async function listTimetables(params?: ListTimetablesParams, options?: RequestInit): Promise<listTimetablesResponse> {
  const res = await fetch(getListTimetablesUrl(params), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: listTimetablesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listTimetablesResponse
}

export function getListTimetablesQueryKey(params?: ListTimetablesParams) {
  return [
    `http://localhost:8080/api/timetables`,
    ...(params ? [params] : []),
  ] as const
}

export function getListTimetablesQueryOptions<TData = Awaited<ReturnType<typeof listTimetables>>, TError = unknown>(params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getListTimetablesQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTimetables>>> = ({ signal }) => listTimetables(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTimetablesQueryResult = NonNullable<Awaited<ReturnType<typeof listTimetables>>>
export type ListTimetablesQueryError = unknown

export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = unknown>(
  params: undefined | ListTimetablesParams, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof listTimetables>>,
      TError,
      Awaited<ReturnType<typeof listTimetables>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = unknown>(
  params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof listTimetables>>,
      TError,
      Awaited<ReturnType<typeof listTimetables>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = unknown>(
  params?: ListTimetablesParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTimetables<TData = Awaited<ReturnType<typeof listTimetables>>, TError = unknown>(
  params?: ListTimetablesParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listTimetables>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListTimetablesQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface createTimetableResponse200 {
  data: string
  status: 200
}

export type createTimetableResponseSuccess = (createTimetableResponse200) & {
  headers: Headers
}

export type createTimetableResponse = (createTimetableResponseSuccess)

export function getCreateTimetableUrl() {
  return `http://localhost:8080/api/timetables`
}

export async function createTimetable(createTimetableRequest: CreateTimetableRequest, options?: RequestInit): Promise<createTimetableResponse> {
  const res = await fetch(getCreateTimetableUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTimetableRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: createTimetableResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTimetableResponse
}

export function getCreateTimetableMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext> {
  const mutationKey = ['createTimetable']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTimetable>>, { data: CreateTimetableRequest }> = (props) => {
    const { data } = props ?? {}

    return createTimetable(data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type CreateTimetableMutationResult = NonNullable<Awaited<ReturnType<typeof createTimetable>>>
export type CreateTimetableMutationBody = CreateTimetableRequest
export type CreateTimetableMutationError = unknown

export function useCreateTimetable<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof createTimetable>>, TError, { data: CreateTimetableRequest }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof createTimetable>>,
  TError,
  { data: CreateTimetableRequest },
  TContext
> {
  return useMutation(getCreateTimetableMutationOptions(options), queryClient)
}

export interface unpublishResponse200 {
  data: void
  status: 200
}

export type unpublishResponseSuccess = (unpublishResponse200) & {
  headers: Headers
}

export type unpublishResponse = (unpublishResponseSuccess)

export function getUnpublishUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/unpublish`
}

export async function unpublish(timetableId: string, options?: RequestInit): Promise<unpublishResponse> {
  const res = await fetch(getUnpublishUrl(timetableId), {
    ...options,
    method: 'POST',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: unpublishResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as unpublishResponse
}

export function getUnpublishMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['unpublish']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof unpublish>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return unpublish(timetableId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type UnpublishMutationResult = NonNullable<Awaited<ReturnType<typeof unpublish>>>

export type UnpublishMutationError = unknown

export function useUnpublish<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof unpublish>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof unpublish>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getUnpublishMutationOptions(options), queryClient)
}

export interface returnToDraftResponse200 {
  data: void
  status: 200
}

export type returnToDraftResponseSuccess = (returnToDraftResponse200) & {
  headers: Headers
}

export type returnToDraftResponse = (returnToDraftResponseSuccess)

export function getReturnToDraftUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/return-to-draft`
}

export async function returnToDraft(timetableId: string, options?: RequestInit): Promise<returnToDraftResponse> {
  const res = await fetch(getReturnToDraftUrl(timetableId), {
    ...options,
    method: 'POST',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: returnToDraftResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as returnToDraftResponse
}

export function getReturnToDraftMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['returnToDraft']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof returnToDraft>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return returnToDraft(timetableId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ReturnToDraftMutationResult = NonNullable<Awaited<ReturnType<typeof returnToDraft>>>

export type ReturnToDraftMutationError = unknown

export function useReturnToDraft<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof returnToDraft>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof returnToDraft>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getReturnToDraftMutationOptions(options), queryClient)
}

export interface publishResponse200 {
  data: void
  status: 200
}

export type publishResponseSuccess = (publishResponse200) & {
  headers: Headers
}

export type publishResponse = (publishResponseSuccess)

export function getPublishUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/publish`
}

export async function publish(timetableId: string, publishRequest: PublishRequest, options?: RequestInit): Promise<publishResponse> {
  const res = await fetch(getPublishUrl(timetableId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publishRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: publishResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as publishResponse
}

export function getPublishMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext> {
  const mutationKey = ['publish']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof publish>>, { timetableId: string, data: PublishRequest }> = (props) => {
    const { timetableId, data } = props ?? {}

    return publish(timetableId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PublishMutationResult = NonNullable<Awaited<ReturnType<typeof publish>>>
export type PublishMutationBody = PublishRequest
export type PublishMutationError = unknown

export function usePublish<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof publish>>, TError, { timetableId: string, data: PublishRequest }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof publish>>,
  TError,
  { timetableId: string, data: PublishRequest },
  TContext
> {
  return useMutation(getPublishMutationOptions(options), queryClient)
}

export interface forwardResponse200 {
  data: void
  status: 200
}

export type forwardResponseSuccess = (forwardResponse200) & {
  headers: Headers
}

export type forwardResponse = (forwardResponseSuccess)

export function getForwardUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/forward`
}

export async function forward(timetableId: string, options?: RequestInit): Promise<forwardResponse> {
  const res = await fetch(getForwardUrl(timetableId), {
    ...options,
    method: 'POST',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: forwardResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as forwardResponse
}

export function getForwardMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext> {
  const mutationKey = ['forward']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof forward>>, { timetableId: string }> = (props) => {
    const { timetableId } = props ?? {}

    return forward(timetableId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ForwardMutationResult = NonNullable<Awaited<ReturnType<typeof forward>>>

export type ForwardMutationError = unknown

export function useForward<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof forward>>, TError, { timetableId: string }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof forward>>,
  TError,
  { timetableId: string },
  TContext
> {
  return useMutation(getForwardMutationOptions(options), queryClient)
}

export interface placeEntryResponse200 {
  data: string
  status: 200
}

export type placeEntryResponseSuccess = (placeEntryResponse200) & {
  headers: Headers
}

export type placeEntryResponse = (placeEntryResponseSuccess)

export function getPlaceEntryUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/entries`
}

export async function placeEntry(timetableId: string, placeEntryRequest: PlaceEntryRequest, options?: RequestInit): Promise<placeEntryResponse> {
  const res = await fetch(getPlaceEntryUrl(timetableId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      placeEntryRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: placeEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as placeEntryResponse
}

export function getPlaceEntryMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext> {
  const mutationKey = ['placeEntry']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof placeEntry>>, { timetableId: string, data: PlaceEntryRequest }> = (props) => {
    const { timetableId, data } = props ?? {}

    return placeEntry(timetableId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type PlaceEntryMutationResult = NonNullable<Awaited<ReturnType<typeof placeEntry>>>
export type PlaceEntryMutationBody = PlaceEntryRequest
export type PlaceEntryMutationError = unknown

export function usePlaceEntry<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof placeEntry>>, TError, { timetableId: string, data: PlaceEntryRequest }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof placeEntry>>,
  TError,
  { timetableId: string, data: PlaceEntryRequest },
  TContext
> {
  return useMutation(getPlaceEntryMutationOptions(options), queryClient)
}

export interface resolveConflictResponse200 {
  data: void
  status: 200
}

export type resolveConflictResponseSuccess = (resolveConflictResponse200) & {
  headers: Headers
}

export type resolveConflictResponse = (resolveConflictResponseSuccess)

export function getResolveConflictUrl(timetableId: string, conflictId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/conflicts/${conflictId}/resolve`
}

export async function resolveConflict(timetableId: string, conflictId: string, resolveConflictRequest: ResolveConflictRequest, options?: RequestInit): Promise<resolveConflictResponse> {
  const res = await fetch(getResolveConflictUrl(timetableId, conflictId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      resolveConflictRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: resolveConflictResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resolveConflictResponse
}

export function getResolveConflictMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext> {
  const mutationKey = ['resolveConflict']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveConflict>>, { timetableId: string, conflictId: string, data: ResolveConflictRequest }> = (props) => {
    const { timetableId, conflictId, data } = props ?? {}

    return resolveConflict(timetableId, conflictId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type ResolveConflictMutationResult = NonNullable<Awaited<ReturnType<typeof resolveConflict>>>
export type ResolveConflictMutationBody = ResolveConflictRequest
export type ResolveConflictMutationError = unknown

export function useResolveConflict<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof resolveConflict>>, TError, { timetableId: string, conflictId: string, data: ResolveConflictRequest }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof resolveConflict>>,
  TError,
  { timetableId: string, conflictId: string, data: ResolveConflictRequest },
  TContext
> {
  return useMutation(getResolveConflictMutationOptions(options), queryClient)
}

export interface moveEntryResponse200 {
  data: void
  status: 200
}

export type moveEntryResponseSuccess = (moveEntryResponse200) & {
  headers: Headers
}

export type moveEntryResponse = (moveEntryResponseSuccess)

export function getMoveEntryUrl(timetableId: string, entryId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/entries/${entryId}/move`
}

export async function moveEntry(timetableId: string, entryId: string, moveEntryRequest: MoveEntryRequest, options?: RequestInit): Promise<moveEntryResponse> {
  const res = await fetch(getMoveEntryUrl(timetableId, entryId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      moveEntryRequest,
    ),
  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: moveEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as moveEntryResponse
}

export function getMoveEntryMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext> {
  const mutationKey = ['moveEntry']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof moveEntry>>, { timetableId: string, entryId: string, data: MoveEntryRequest }> = (props) => {
    const { timetableId, entryId, data } = props ?? {}

    return moveEntry(timetableId, entryId, data, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type MoveEntryMutationResult = NonNullable<Awaited<ReturnType<typeof moveEntry>>>
export type MoveEntryMutationBody = MoveEntryRequest
export type MoveEntryMutationError = unknown

export function useMoveEntry<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof moveEntry>>, TError, { timetableId: string, entryId: string, data: MoveEntryRequest }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof moveEntry>>,
  TError,
  { timetableId: string, entryId: string, data: MoveEntryRequest },
  TContext
> {
  return useMutation(getMoveEntryMutationOptions(options), queryClient)
}

export interface getTimetableGridResponse200 {
  data: TimetableGridView
  status: 200
}

export type getTimetableGridResponseSuccess = (getTimetableGridResponse200) & {
  headers: Headers
}

export type getTimetableGridResponse = (getTimetableGridResponseSuccess)

export function getGetTimetableGridUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}`
}

export async function getTimetableGrid(timetableId: string, options?: RequestInit): Promise<getTimetableGridResponse> {
  const res = await fetch(getGetTimetableGridUrl(timetableId), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getTimetableGridResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getTimetableGridResponse
}

export function getGetTimetableGridQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}`,
  ] as const
}

export function getGetTimetableGridQueryOptions<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = unknown>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetTimetableGridQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTimetableGrid>>> = ({ signal }) => getTimetableGrid(timetableId, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTimetableGridQueryResult = NonNullable<Awaited<ReturnType<typeof getTimetableGrid>>>
export type GetTimetableGridQueryError = unknown

export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = unknown>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getTimetableGrid>>,
      TError,
      Awaited<ReturnType<typeof getTimetableGrid>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getTimetableGrid>>,
      TError,
      Awaited<ReturnType<typeof getTimetableGrid>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTimetableGrid<TData = Awaited<ReturnType<typeof getTimetableGrid>>, TError = unknown>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTimetableGrid>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTimetableGridQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getConflictsResponse200 {
  data: ConflictSummaryView[]
  status: 200
}

export type getConflictsResponseSuccess = (getConflictsResponse200) & {
  headers: Headers
}

export type getConflictsResponse = (getConflictsResponseSuccess)

export function getGetConflictsUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/conflicts`
}

export async function getConflicts(timetableId: string, options?: RequestInit): Promise<getConflictsResponse> {
  const res = await fetch(getGetConflictsUrl(timetableId), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getConflictsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getConflictsResponse
}

export function getGetConflictsQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}/conflicts`,
  ] as const
}

export function getGetConflictsQueryOptions<TData = Awaited<ReturnType<typeof getConflicts>>, TError = unknown>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetConflictsQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getConflicts>>> = ({ signal }) => getConflicts(timetableId, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConflictsQueryResult = NonNullable<Awaited<ReturnType<typeof getConflicts>>>
export type GetConflictsQueryError = unknown

export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = unknown>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getConflicts>>,
      TError,
      Awaited<ReturnType<typeof getConflicts>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getConflicts>>,
      TError,
      Awaited<ReturnType<typeof getConflicts>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetConflicts<TData = Awaited<ReturnType<typeof getConflicts>>, TError = unknown>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getConflicts>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetConflictsQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getAvailableSlotsResponse200 {
  data: SlotView[]
  status: 200
}

export type getAvailableSlotsResponseSuccess = (getAvailableSlotsResponse200) & {
  headers: Headers
}

export type getAvailableSlotsResponse = (getAvailableSlotsResponseSuccess)

export function getGetAvailableSlotsUrl(timetableId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/available-slots`
}

export async function getAvailableSlots(timetableId: string, options?: RequestInit): Promise<getAvailableSlotsResponse> {
  const res = await fetch(getGetAvailableSlotsUrl(timetableId), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAvailableSlotsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAvailableSlotsResponse
}

export function getGetAvailableSlotsQueryKey(timetableId: string) {
  return [
    `http://localhost:8080/api/timetables/${timetableId}/available-slots`,
  ] as const
}

export function getGetAvailableSlotsQueryOptions<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = unknown>(timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAvailableSlotsQueryKey(timetableId)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAvailableSlots>>> = ({ signal }) => getAvailableSlots(timetableId, { signal, ...fetchOptions })

  return { queryKey, queryFn, enabled: !!(timetableId), ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAvailableSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getAvailableSlots>>>
export type GetAvailableSlotsQueryError = unknown

export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = unknown>(
  timetableId: string, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAvailableSlots>>,
      TError,
      Awaited<ReturnType<typeof getAvailableSlots>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAvailableSlots>>,
      TError,
      Awaited<ReturnType<typeof getAvailableSlots>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = unknown>(
  timetableId: string, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAvailableSlots<TData = Awaited<ReturnType<typeof getAvailableSlots>>, TError = unknown>(
  timetableId: string,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAvailableSlots>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAvailableSlotsQueryOptions(timetableId, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getSlotsResponse200 {
  data: LegacyLessonSlotGroup[]
  status: 200
}

export type getSlotsResponseSuccess = (getSlotsResponse200) & {
  headers: Headers
}

export type getSlotsResponse = (getSlotsResponseSuccess)

export function getGetSlotsUrl() {
  return `http://localhost:8080/api/acl/slots`
}

export async function getSlots(options?: RequestInit): Promise<getSlotsResponse> {
  const res = await fetch(getGetSlotsUrl(), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getSlotsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSlotsResponse
}

export function getGetSlotsQueryKey() {
  return [
    `http://localhost:8080/api/acl/slots`,
  ] as const
}

export function getGetSlotsQueryOptions<TData = Awaited<ReturnType<typeof getSlots>>, TError = unknown>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetSlotsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSlots>>> = ({ signal }) => getSlots({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSlotsQueryResult = NonNullable<Awaited<ReturnType<typeof getSlots>>>
export type GetSlotsQueryError = unknown

export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = unknown>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getSlots>>,
      TError,
      Awaited<ReturnType<typeof getSlots>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getSlots>>,
      TError,
      Awaited<ReturnType<typeof getSlots>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetSlots<TData = Awaited<ReturnType<typeof getSlots>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getSlots>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSlotsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getRoomsResponse200 {
  data: LegacyCampusRoomGroup[]
  status: 200
}

export type getRoomsResponseSuccess = (getRoomsResponse200) & {
  headers: Headers
}

export type getRoomsResponse = (getRoomsResponseSuccess)

export function getGetRoomsUrl() {
  return `http://localhost:8080/api/acl/rooms`
}

export async function getRooms(options?: RequestInit): Promise<getRoomsResponse> {
  const res = await fetch(getGetRoomsUrl(), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getRoomsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRoomsResponse
}

export function getGetRoomsQueryKey() {
  return [
    `http://localhost:8080/api/acl/rooms`,
  ] as const
}

export function getGetRoomsQueryOptions<TData = Awaited<ReturnType<typeof getRooms>>, TError = unknown>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetRoomsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getRooms>>> = ({ signal }) => getRooms({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRoomsQueryResult = NonNullable<Awaited<ReturnType<typeof getRooms>>>
export type GetRoomsQueryError = unknown

export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = unknown>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getRooms>>,
      TError,
      Awaited<ReturnType<typeof getRooms>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getRooms>>,
      TError,
      Awaited<ReturnType<typeof getRooms>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetRooms<TData = Awaited<ReturnType<typeof getRooms>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getRooms>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetRoomsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getDepartmentsResponse200 {
  data: LegacyDepartmentResponse[]
  status: 200
}

export type getDepartmentsResponseSuccess = (getDepartmentsResponse200) & {
  headers: Headers
}

export type getDepartmentsResponse = (getDepartmentsResponseSuccess)

export function getGetDepartmentsUrl() {
  return `http://localhost:8080/api/acl/departments`
}

export async function getDepartments(options?: RequestInit): Promise<getDepartmentsResponse> {
  const res = await fetch(getGetDepartmentsUrl(), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getDepartmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getDepartmentsResponse
}

export function getGetDepartmentsQueryKey() {
  return [
    `http://localhost:8080/api/acl/departments`,
  ] as const
}

export function getGetDepartmentsQueryOptions<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetDepartmentsQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDepartments>>> = ({ signal }) => getDepartments({ signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDepartmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getDepartments>>>
export type GetDepartmentsQueryError = unknown

export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
  options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getDepartments>>,
      TError,
      Awaited<ReturnType<typeof getDepartments>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getDepartments>>,
      TError,
      Awaited<ReturnType<typeof getDepartments>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDepartments<TData = Awaited<ReturnType<typeof getDepartments>>, TError = unknown>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getDepartments>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetDepartmentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getCohortsResponse200 {
  data: LegacyCohortResponse[]
  status: 200
}

export type getCohortsResponseSuccess = (getCohortsResponse200) & {
  headers: Headers
}

export type getCohortsResponse = (getCohortsResponseSuccess)

export function getGetCohortsUrl(params: GetCohortsParams) {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/acl/cohorts?${stringifiedParams}` : `http://localhost:8080/api/acl/cohorts`
}

export async function getCohorts(params: GetCohortsParams, options?: RequestInit): Promise<getCohortsResponse> {
  const res = await fetch(getGetCohortsUrl(params), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getCohortsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCohortsResponse
}

export function getGetCohortsQueryKey(params?: GetCohortsParams) {
  return [
    `http://localhost:8080/api/acl/cohorts`,
    ...(params ? [params] : []),
  ] as const
}

export function getGetCohortsQueryOptions<TData = Awaited<ReturnType<typeof getCohorts>>, TError = unknown>(params: GetCohortsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetCohortsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCohorts>>> = ({ signal }) => getCohorts(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCohortsQueryResult = NonNullable<Awaited<ReturnType<typeof getCohorts>>>
export type GetCohortsQueryError = unknown

export function useGetCohorts<TData = Awaited<ReturnType<typeof getCohorts>>, TError = unknown>(
  params: GetCohortsParams, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getCohorts>>,
      TError,
      Awaited<ReturnType<typeof getCohorts>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCohorts<TData = Awaited<ReturnType<typeof getCohorts>>, TError = unknown>(
  params: GetCohortsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getCohorts>>,
      TError,
      Awaited<ReturnType<typeof getCohorts>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCohorts<TData = Awaited<ReturnType<typeof getCohorts>>, TError = unknown>(
  params: GetCohortsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCohorts<TData = Awaited<ReturnType<typeof getCohorts>>, TError = unknown>(
  params: GetCohortsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getCohorts>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetCohortsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface getAllAssignmentsResponse200 {
  data: ApprovedAssignment[]
  status: 200
}

export type getAllAssignmentsResponseSuccess = (getAllAssignmentsResponse200) & {
  headers: Headers
}

export type getAllAssignmentsResponse = (getAllAssignmentsResponseSuccess)

export function getGetAllAssignmentsUrl(params: GetAllAssignmentsParams) {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `http://localhost:8080/api/acl/assignments?${stringifiedParams}` : `http://localhost:8080/api/acl/assignments`
}

export async function getAllAssignments(params: GetAllAssignmentsParams, options?: RequestInit): Promise<getAllAssignmentsResponse> {
  const res = await fetch(getGetAllAssignmentsUrl(params), {
    ...options,
    method: 'GET',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: getAllAssignmentsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllAssignmentsResponse
}

export function getGetAllAssignmentsQueryKey(params?: GetAllAssignmentsParams) {
  return [
    `http://localhost:8080/api/acl/assignments`,
    ...(params ? [params] : []),
  ] as const
}

export function getGetAllAssignmentsQueryOptions<TData = Awaited<ReturnType<typeof getAllAssignments>>, TError = unknown>(params: GetAllAssignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData>>, fetch?: RequestInit }) {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {}

  const queryKey = queryOptions?.queryKey ?? getGetAllAssignmentsQueryKey(params)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllAssignments>>> = ({ signal }) => getAllAssignments(params, { signal, ...fetchOptions })

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllAssignmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllAssignments>>>
export type GetAllAssignmentsQueryError = unknown

export function useGetAllAssignments<TData = Awaited<ReturnType<typeof getAllAssignments>>, TError = unknown>(
  params: GetAllAssignmentsParams, options: { query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData>> & Pick<
    DefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAllAssignments>>,
      TError,
      Awaited<ReturnType<typeof getAllAssignments>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAssignments<TData = Awaited<ReturnType<typeof getAllAssignments>>, TError = unknown>(
  params: GetAllAssignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData>> & Pick<
    UndefinedInitialDataOptions<
      Awaited<ReturnType<typeof getAllAssignments>>,
      TError,
      Awaited<ReturnType<typeof getAllAssignments>>
    >,
    'initialData'
  >, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllAssignments<TData = Awaited<ReturnType<typeof getAllAssignments>>, TError = unknown>(
  params: GetAllAssignmentsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllAssignments<TData = Awaited<ReturnType<typeof getAllAssignments>>, TError = unknown>(
  params: GetAllAssignmentsParams,
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllAssignments>>, TError, TData>>, fetch?: RequestInit },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAllAssignmentsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

  return { ...query, queryKey: queryOptions.queryKey }
}

export interface removeEntryResponse200 {
  data: void
  status: 200
}

export type removeEntryResponseSuccess = (removeEntryResponse200) & {
  headers: Headers
}

export type removeEntryResponse = (removeEntryResponseSuccess)

export function getRemoveEntryUrl(timetableId: string, entryId: string) {
  return `http://localhost:8080/api/timetables/${timetableId}/entries/${entryId}`
}

export async function removeEntry(timetableId: string, entryId: string, options?: RequestInit): Promise<removeEntryResponse> {
  const res = await fetch(getRemoveEntryUrl(timetableId, entryId), {
    ...options,
    method: 'DELETE',

  })

  const body = [204, 205, 304].includes(res.status) ? null : await res.text()

  const data: removeEntryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeEntryResponse
}

export function getRemoveEntryMutationOptions<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext>, fetch?: RequestInit }): UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext> {
  const mutationKey = ['removeEntry']
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined }

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeEntry>>, { timetableId: string, entryId: string }> = (props) => {
    const { timetableId, entryId } = props ?? {}

    return removeEntry(timetableId, entryId, fetchOptions)
  }

  return { mutationFn, ...mutationOptions }
}

export type RemoveEntryMutationResult = NonNullable<Awaited<ReturnType<typeof removeEntry>>>

export type RemoveEntryMutationError = unknown

export function useRemoveEntry<TError = unknown, TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof removeEntry>>, TError, { timetableId: string, entryId: string }, TContext>, fetch?: RequestInit }, queryClient?: QueryClient): UseMutationResult<
  Awaited<ReturnType<typeof removeEntry>>,
  TError,
  { timetableId: string, entryId: string },
  TContext
> {
  return useMutation(getRemoveEntryMutationOptions(options), queryClient)
}
