/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardDepartmentsIndexRouteImport } from './routes/dashboard/departments/index'
import { Route as DashboardDepartmentsDepartmentIdRouteImport } from './routes/dashboard/departments/$departmentId'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDepartmentsIndexRoute =
  DashboardDepartmentsIndexRouteImport.update({
    id: '/departments/',
    path: '/departments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDepartmentsDepartmentIdRoute =
  DashboardDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/departments/$departmentId': typeof DashboardDepartmentsDepartmentIdRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/departments/$departmentId': typeof DashboardDepartmentsDepartmentIdRoute
  '/dashboard/departments': typeof DashboardDepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/departments/$departmentId': typeof DashboardDepartmentsDepartmentIdRoute
  '/dashboard/departments/': typeof DashboardDepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/departments/$departmentId'
    | '/dashboard/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/departments/$departmentId'
    | '/dashboard/departments'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/departments/$departmentId'
    | '/dashboard/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/departments/': {
      id: '/dashboard/departments/'
      path: '/departments'
      fullPath: '/dashboard/departments/'
      preLoaderRoute: typeof DashboardDepartmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/departments/$departmentId': {
      id: '/dashboard/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/dashboard/departments/$departmentId'
      preLoaderRoute: typeof DashboardDepartmentsDepartmentIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDepartmentsDepartmentIdRoute: typeof DashboardDepartmentsDepartmentIdRoute
  DashboardDepartmentsIndexRoute: typeof DashboardDepartmentsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDepartmentsDepartmentIdRoute: DashboardDepartmentsDepartmentIdRoute,
  DashboardDepartmentsIndexRoute: DashboardDepartmentsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
